name: ssht

on:
  push:
    branches: [ main ]
    paths:
      - "docker_sync/images/ssht.json"
      - "docker_sync/*.py"
      - ".github/workflows/ssht.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NAME: ssht
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: AliYun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Sync Docker image
        run: |
          python docker_sync ${{ env.NAME }}
